import type { PaneTabsApi } from "../pane-tabs/use-pane-tabs.ts";
import type { SetupTmuxRuntimeContext, SetupTmuxRuntimeSessionRuntimeContext } from "../runtime/runtime-context.ts";
import type { AgentActionsApi } from "./use-agent-actions.ts";
import type { AppRuntimeRefs } from "./use-app-runtime-refs.ts";
import type { AgentDialogState, TmuxSessionState, UiChromeState } from "./use-app-state-groups.ts";
import type { HistoryWorkflowApi } from "./use-history-workflow.ts";
import type { LayoutProfilesApi } from "./use-layout-profiles.ts";
import type { OptionsWorkflowApi } from "./use-options-workflow.ts";
import type { TabActionsApi } from "./use-tab-actions.ts";
import type { UiActionsApi } from "./use-ui-actions.ts";

interface BuildAppRuntimeContextOptions {
  agentActions: AgentActionsApi;
  agentDialogState: AgentDialogState;
  historyWorkflow: HistoryWorkflowApi;
  layoutProfiles: LayoutProfilesApi;
  optionsWorkflow: OptionsWorkflowApi;
  paneTabsApi: PaneTabsApi;
  refs: AppRuntimeRefs;
  renderer: SetupTmuxRuntimeSessionRuntimeContext["renderer"];
  spawnPtyBridge: (targetSession: string) => unknown;
  tabActions: TabActionsApi;
  tmuxSessionState: TmuxSessionState;
  uiActions: UiActionsApi;
  uiChromeState: UiChromeState;
}

export function buildAppRuntimeContext({
  agentActions,
  agentDialogState,
  historyWorkflow,
  layoutProfiles,
  optionsWorkflow,
  paneTabsApi,
  refs,
  renderer,
  spawnPtyBridge,
  tabActions,
  tmuxSessionState,
  uiActions,
  uiChromeState,
}: BuildAppRuntimeContextOptions): SetupTmuxRuntimeContext {
  return {
    agentRuntime: {
      activePaneIdRef: refs.activePaneIdRef,
      muxotronExpandedRef: refs.muxotronExpandedRef,
      registryRef: refs.registryRef,
      setAgentSessions: agentDialogState.setAgentSessions,
      setClaudeDialogPending: agentDialogState.setClaudeDialogPending,
      setCodexDialogPending: agentDialogState.setCodexDialogPending,
      setGeminiDialogPending: agentDialogState.setGeminiDialogPending,
      setHookSnifferEvents: agentDialogState.setHookSnifferEvents,
      setOpenCodeDialogPending: agentDialogState.setOpenCodeDialogPending,
      storeRef: refs.storeRef,
      uiModeRef: refs.uiModeRef,
    },
    configRuntime: {
      setConfig: optionsWorkflow.setConfig,
      setConfigThemeBuiltin: optionsWorkflow.setConfigThemeBuiltin,
      setConfigThemeMode: optionsWorkflow.setConfigThemeMode,
      setConfigUIMode: optionsWorkflow.setConfigUIMode,
      setToolbarOpen: uiChromeState.setToolbarOpen,
    },
    dialogs: {
      agentInstallDialogRef: refs.agentInstallDialogRef,
      dialogInputRef: refs.dialogInputRef,
      dropdownInputRef: refs.dropdownInputRef,
      mainMenuCapturingRef: refs.mainMenuCapturingRef,
      optionsDialogCapturingRef: refs.optionsDialogCapturingRef,
      setMainMenuDialogOpen: uiChromeState.setMainMenuDialogOpen,
    },
    input: {
      agentPreviewRef: refs.agentPreviewRef,
      extendedKeysActiveRef: refs.extendedKeysActiveRef,
      handleActivateMenuRef: refs.handleActivateMenuRef,
      handleAgentLatchRef: refs.handleAgentLatchRef,
      handleAgentNextRef: refs.handleAgentNextRef,
      handleAgentPrevRef: refs.handleAgentPrevRef,
      handleApplyFavoriteProfile: layoutProfiles.handleApplyFavoriteProfile,
      handleBufferZoomRef: refs.handleBufferZoomRef,
      handleCloseQuickTerminalRef: refs.handleCloseQuickTerminalRef,
      handleDismissRef: refs.handleDismissRef,
      handleExitMobileModeRef: refs.handleExitMobileModeRef,
      handleGotoAgentRef: refs.handleGotoAgentRef,
      handleLayoutProfileClick: layoutProfiles.handleLayoutProfileClick,
      handleMobileToggleRef: refs.handleMobileToggleRef,
      handleMuxotronDismissRef: refs.handleMuxotronDismissRef,
      handleNewPaneTabRef: refs.handleNewPaneTabRef,
      handleNextPaneTabRef: refs.handleNextPaneTabRef,
      handleNotificationsClickRef: refs.handleNotificationsClickRef,
      handleOpenAgentsDialog: agentActions.handleOpenAgentsDialog,
      handleOpenConversationsRef: historyWorkflow.handleOpenConversationsRef,
      handleOpenQuickTerminalRef: refs.handleOpenQuickTerminalRef,
      handleOptionsClickRef: refs.handleOptionsClickRef,
      handlePrevPaneTabRef: refs.handlePrevPaneTabRef,
      handleQuickApproveRef: refs.handleQuickApproveRef,
      handleQuickDenyRef: refs.handleQuickDenyRef,
      handleRedrawRef: refs.handleRedrawRef,
      handleReviewAgentRef: refs.handleReviewAgentRef,
      handleScreenshotRef: refs.handleScreenshotRef,
      handleSessionClickRef: refs.handleSessionClickRef,
      handleSessionNextRef: refs.handleSessionNextRef,
      handleSessionPrevRef: refs.handleSessionPrevRef,
      handleSidebarActivateRef: refs.handleSidebarActivateRef,
      handleSidebarCancelRef: refs.handleSidebarCancelRef,
      handleSidebarDownRef: refs.handleSidebarDownRef,
      handleSidebarFocusRef: refs.handleSidebarFocusRef,
      handleSidebarLeftRef: refs.handleSidebarLeftRef,
      handleSidebarRightRef: refs.handleSidebarRightRef,
      handleSidebarToggleRef: refs.handleSidebarToggleRef,
      handleSidebarUpRef: refs.handleSidebarUpRef,
      handleSidebarZoomRef: refs.handleSidebarZoomRef,
      handleTabNext: tabActions.handleTabNext,
      handleTabPrev: tabActions.handleTabPrev,
      handleTextInputEscape: uiActions.handleTextInputEscape,
      handleToolbarActivateRef: refs.handleToolbarActivateRef,
      handleToolbarCancelRef: refs.handleToolbarCancelRef,
      handleToolbarDismissRef: refs.handleToolbarDismissRef,
      handleToolbarDownRef: refs.handleToolbarDownRef,
      handleToolbarFocusRef: refs.handleToolbarFocusRef,
      handleToolbarToggleRef: refs.handleToolbarToggleRef,
      handleToolbarUpRef: refs.handleToolbarUpRef,
      handleZoomEndRef: refs.handleZoomEndRef,
      handleZoomStartRef: refs.handleZoomStartRef,
      interactiveAgentRef: refs.interactiveAgentRef,
      matchZoomCodeRef: refs.matchZoomCodeRef,
      muxotronFocusActiveRef: refs.muxotronFocusActiveRef,
      paneTabBorderClickRef: paneTabsApi.paneTabBorderClickRef,
      reEncodeActiveRef: refs.reEncodeActiveRef,
      reviewLatchedRef: refs.reviewLatchedRef,
      sequenceMapRef: refs.sequenceMapRef,
      showHintRef: refs.showHintRef,
      sidebarFocusedIndexRef: refs.sidebarFocusedIndexRef,
      sidebarFocusedRef: refs.sidebarFocusedRef,
      sidebarItemCountRef: refs.sidebarItemCountRef,
      tmuxPrefixKeyAliasRef: refs.tmuxPrefixKeyAliasRef,
      tmuxPrefixSequenceRef: refs.tmuxPrefixSequenceRef,
      toggleReviewLatchRef: refs.toggleReviewLatchRef,
      toolbarFocusedIndexRef: refs.toolbarFocusedIndexRef,
      toolbarInputRef: refs.toolbarInputRef,
      toolbarOpenRef: refs.toolbarOpenRef,
      validateTabGroups: paneTabsApi.validateTabGroups,
      writeFnRef: refs.writeFnRef,
      zoomActionRef: refs.zoomActionRef,
      zoomStickyRef: refs.zoomStickyRef,
    },
    mouse: {
      agentsDialogOpenRef: agentDialogState.agentsDialogOpenRef,
      dropdownOpenRef: uiChromeState.dropdownOpenRef,
      ignoreMouseInputRef: refs.ignoreMouseInputRef,
      layoutDropdownOpenRef: refs.layoutDropdownOpenRef,
      mainMenuDialogOpenRef: uiChromeState.mainMenuDialogOpenRef,
      mobileModeRef: refs.mobileModeRef,
      muxotronExpandedRef: refs.muxotronExpandedRef,
      overflowOpenRef: refs.overflowOpenRef,
      overlayOpenRef: agentDialogState.overlayOpenRef,
      paneTabBorderHitTestRef: paneTabsApi.paneTabBorderHitTestRef,
      paneTabBorderRightClickRef: paneTabsApi.paneTabBorderRightClickRef,
      paneTabDragEndRef: paneTabsApi.paneTabDragEndRef,
      paneTabDragMoveRef: paneTabsApi.paneTabDragMoveRef,
      paneTabDraggingRef: paneTabsApi.paneTabDraggingRef,
      qtResizeDragEndRef: refs.qtResizeDragEndRef,
      qtResizeDragMoveRef: refs.qtResizeDragMoveRef,
      qtResizeDraggingRef: refs.qtResizeDraggingRef,
      qtResizeSizeRef: refs.qtResizeSizeRef,
      quickTerminalMenuOpenRef: refs.quickTerminalMenuOpenRef,
      quickTerminalOpenRef: agentDialogState.quickTerminalOpenRef,
      sidebarDragEndRef: refs.sidebarDragEndRef,
      sidebarDragMoveRef: refs.sidebarDragMoveRef,
      sidebarDraggingRef: refs.sidebarDraggingRef,
      sidebarOpenRef: refs.sidebarOpenRef,
      sidebarWidthRef: refs.sidebarWidthRef,
      statusBarBottomOffsetRef: refs.statusBarBottomOffsetRef,
      statusBarClickRef: refs.statusBarClickRef,
      statusBarTopOffsetRef: refs.statusBarTopOffsetRef,
      tabDragEndRef: refs.tabDragEndRef,
      tabDragMoveRef: refs.tabDragMoveRef,
      tabDraggingRef: refs.tabDraggingRef,
      tabPressOriginRef: refs.tabPressOriginRef,
      tabRightClickRef: refs.tabRightClickRef,
      uiModeRef: refs.uiModeRef,
    },
    sessionRuntime: {
      clientRef: refs.clientRef,
      deferredSessionRef: refs.deferredSessionRef,
      detachingRef: tmuxSessionState.detachingRef,
      dimsRef: refs.dimsRef,
      initTargetRef: tmuxSessionState.initTargetRef,
      inputReady: refs.inputReady,
      inputRouterSetup: refs.inputRouterSetup,
      promptClickStateRef: refs.promptClickStateRef,
      promptInputStartRef: refs.promptInputStartRef,
      ptyRef: refs.ptyRef,
      remoteManagerRef: refs.remoteManagerRef,
      renderer,
      spawnPtyBridge,
      switchingRef: tmuxSessionState.switchingRef,
      terminalRef: refs.terminalRef,
      textInputActive: refs.textInputActive,
      tooNarrowRef: refs.tooNarrowRef,
    },
    sessionState: {
      historyLoadStartedRef: historyWorkflow.historyLoadStartedRef,
      setActiveIndex: tmuxSessionState.setActiveIndex,
      setConnected: tmuxSessionState.setConnected,
      setCurrentSessionName: tmuxSessionState.setCurrentSessionName,
      setHistoryReady: historyWorkflow.setHistoryReady,
      setKeyBindings: tmuxSessionState.setKeyBindings,
      setSessionKey: tmuxSessionState.setSessionKey,
      setSessions: tmuxSessionState.setSessions,
      setStatusBarInfo: tmuxSessionState.setStatusBarInfo,
      setWindows: tmuxSessionState.setWindows,
    },
  };
}
