#!/usr/bin/env bun
//
// generate-takumi-shim.ts — emit a host-platform-specific dynamic import for
// @takumi-rs/core's NAPI binding so `bun build --compile` embeds the .node
// file into the standalone binary.
//
// Background: takumi (used by ghostty-opentui's image renderer) loads its
// native binding via createRequire-based dynamic require(), which Bun's
// bundler does not follow as an asset reference. The compiled binary
// therefore ships without the .node file and screenshots fail at runtime
// with "Cannot find native binding". By emitting an `import(...) with
// { type: "file" }`, Bun embeds the binding as an asset; takumi's
// `requireNative()` already honors NAPI_RS_NATIVE_LIBRARY_PATH, which we
// point at the extracted path before importing @takumi-rs/core.
//
// The generated file is platform-specific. It lives under
// node_modules/.cache (the find-cache-dir convention) and is exposed via
// the "@hmx/takumi-native-path" alias in tsconfig's "paths" field, so
// callers don't depend on its location. It must be regenerated whenever
// the build host changes.

import { mkdirSync, writeFileSync } from "fs";
import { dirname, join, resolve } from "path";

const ROOT = resolve(import.meta.dirname!, "..");
// Generated under node_modules/.cache so the file lives in an already-ignored
// path and the source tree stays clean. Consumers import it via the
// "@hmx/takumi-native-path" alias declared in tsconfig.json's "paths" field.
const OUT = join(ROOT, "node_modules", ".cache", "honeymux", "takumi-native-path.ts");

interface Target {
  nodeFile: string;
  pkg: string;
}

function detectTarget(): Target {
  const { arch, platform } = process;
  if (platform === "darwin" && arch === "arm64") {
    return { nodeFile: "core.darwin-arm64.node", pkg: "@takumi-rs/core-darwin-arm64" };
  }
  if (platform === "darwin" && arch === "x64") {
    return { nodeFile: "core.darwin-x64.node", pkg: "@takumi-rs/core-darwin-x64" };
  }
  if (platform === "linux" && arch === "arm64") {
    return { nodeFile: "core.linux-arm64-gnu.node", pkg: "@takumi-rs/core-linux-arm64-gnu" };
  }
  if (platform === "linux" && arch === "x64") {
    return { nodeFile: "core.linux-x64-gnu.node", pkg: "@takumi-rs/core-linux-x64-gnu" };
  }
  throw new Error(`Unsupported build host: ${platform}/${arch}`);
}

const { nodeFile, pkg } = detectTarget();
const content = `// Auto-generated by scripts/generate-takumi-shim.ts. Do not edit.
// Regenerate by running: bun scripts/generate-takumi-shim.ts
//
// In compiled mode (bun --compile), the dynamic-import-as-file form embeds
// the .node as an asset and resolves to the runtime extraction path. In dev
// mode (bun run), the same import throws because Bun rejects loading .node
// files via ES import even with type:"file" — that's fine, takumi's normal
// NAPI-RS dispatch finds the binding in node_modules. The catch lets us
// share one code path between both modes.
let napiPath: string | undefined;
try {
  const mod = await import("${pkg}/${nodeFile}", { with: { type: "file" } });
  napiPath = mod.default as string;
} catch {
  napiPath = undefined;
}

export default napiPath;
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, content);
console.log(`generate-takumi-shim: wrote ${OUT} (${pkg}/${nodeFile})`);
